on: [push, pull_request]

name: Continuous Integration

jobs:
  check:
    name: cargo-check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - stable minus 8 releases
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - name: check default-features
        run: cargo check

      - name: check all-features
        run: cargo check --all-features

  check-minimal-versions:
    name: cargo-check-minimal-versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@nightly
      - name: Update dependencies to minimal versions
        run: cargo update -Z minimal-versions

      - name: cargo check (minimal versions)
        run: cargo check

      - name: cargo check --all-features (minimal versions)
        run: cargo check --all-features


  test:
    name: cargo-test ...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: test
        run: cargo test

      - name: test (with parser)
        run: cargo test --features parser

      - name: test (with TZ)
        run: cargo test --features chrono-tz

  fmtclippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2

      - name: cargo-clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: cargo-fmt
        run: cargo fmt --all --check

  deny-check:
    name: cargo-deny check
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.checks }}
          arguments: --all-features
